# Generated by Django 5.2.6 on 2025-11-24 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('sick', 'Sick'), ('vacation', 'Vacation'), ('seminar', 'Seminar'), ('leave', 'Casual Leave')], default='present', max_length=16)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendance', to='core.employee')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
