# Generated by Django 5.2.6 on 2025-11-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dailyattendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='supervisor',
            new_name='supervisor_id',
        ),
        migrations.RenameField(
            model_name='supervisor',
            old_name='manager',
            new_name='manager_id',
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('sick', 'Sick'), ('vacation', 'Vacation'), ('seminar', 'Seminar')], default='present', max_length=16),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('sick', 'Sick'), ('vacation', 'Vacation'), ('seminar', 'Seminar')], default='present', max_length=16),
        ),
    ]
